# Generated by Django 6.0.6 on 2026-06-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
