# Generated by Django 6.0.6 on 2026-06-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursefile',
            options={'ordering': ['day', 'order']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['day', 'order']},
        ),
        migrations.AddField(
            model_name='coursefile',
            name='day',
            field=models.PositiveIntegerField(default=1, help_text='Day number for this content'),
        ),
        migrations.AddField(
            model_name='video',
            name='day',
            field=models.PositiveIntegerField(default=1, help_text='Day number for this content'),
        ),
    ]
