# Generated by Django 6.0.6 on 2026-06-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0007_course_duration_course_learning_outcomes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of attempts allowed'),
        ),
        migrations.AddField(
            model_name='test',
            name='time_per_question',
            field=models.PositiveIntegerField(default=60, help_text='Time per question in seconds'),
        ),
    ]
