# Generated by Django 6.0.6 on 2026-06-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0008_test_max_attempts_test_time_per_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='download_permission',
            field=models.CharField(choices=[('download', 'Download Allowed'), ('view_only', 'View Only')], default='view_only', max_length=10),
        ),
    ]
