# Generated by Django 6.0.6 on 2026-06-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0009_coursefile_download_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='allow_download',
            field=models.BooleanField(default=False, help_text='Allow users to download this file'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='allow_streaming',
            field=models.BooleanField(default=True, help_text='Allow users to view this file'),
        ),
        migrations.AddField(
            model_name='test',
            name='allow_download',
            field=models.BooleanField(default=False, help_text='Allow users to download test questions'),
        ),
        migrations.AddField(
            model_name='test',
            name='allow_streaming',
            field=models.BooleanField(default=True, help_text='Allow users to take this test'),
        ),
        migrations.AddField(
            model_name='video',
            name='allow_download',
            field=models.BooleanField(default=False, help_text='Allow users to download this video'),
        ),
        migrations.AddField(
            model_name='video',
            name='allow_streaming',
            field=models.BooleanField(default=True, help_text='Allow users to stream this video'),
        ),
    ]
