# Generated by Django 6.0.6 on 2026-06-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0010_coursefile_allow_download_coursefile_allow_streaming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1, help_text='Marks for this question'),
        ),
    ]
